import { Component, OnInit } from '@angular/core';
import { Platform, ModalController } from '@ionic/angular';
import { Geolocation } from '@ionic-native/geolocation/ngx';
import { ModalPlaceDataPage } from '../modal-place-data/modal-place-data.page';
import { QuadrantsService } from '../api/quadrants.service';
import {
  GoogleMaps,
  GoogleMap,
  GoogleMapsEvent,
  BaseArrayClass,
  ILatLng,
  Poly
} from '@ionic-native/google-maps';


@Component({
  selector: 'app-quadrants',
  templateUrl: './quadrants.page.html',
  styleUrls: ['./quadrants.page.scss'],
})
export class QuadrantsPage implements OnInit {

  map: GoogleMap;

  subscription: any;
  lat: number;
  lng: number;
  cuadranteActual: ILatLng[];

  cuadrantes: ILatLng[][];

  constructor(
      private platform: Platform,
      private quadrant: QuadrantsService,
      private geolocation: Geolocation,
      private modalController: ModalController
  ) {
    this.cuadrantes = quadrant.all();

  }

  async presentModal(latLng) {
    const modal = await this.modalController.create({
      component: ModalPlaceDataPage,
      componentProps: { latLng: latLng, subscription: this.subscription }
    });
    return await modal.present();
  }


    ionViewDidEnter() {
        this._getCoords();
    }

  private _getCoords() {
    const watch = this.geolocation.watchPosition();
    this.subscription = watch.subscribe((data) => {
      this.lat = data.coords.latitude;
      this.lng = data.coords.longitude;
      console.log(this.lat + ', ' +  this.lng);

      for ( let i = 0; i < this.cuadrantes.length; i++ ) {
        // if (Poly.containsLocation({ lat: 19.776817, lng: -98.976382 }, this.cuadrantes[i]) ) {
        if (Poly.containsLocation({ lat: this.lat, lng: this.lng }, this.cuadrantes[i]) ) {
          if (this.cuadranteActual !== this.cuadrantes[i]) {
            this.cuadranteActual = this.cuadrantes[i];
            this.map.moveCamera({target: this.cuadranteActual});
            this.map.addPolygonSync({
              'points': this.cuadranteActual,
              'strokeColor' : 'rgba(84,0,14)',
              'fillColor' : 'rgba(84,0,14,0.2)',
              'strokeWidth': 3
            });
          }
        }
      }


    });
  }

  ionViewWillLeave() {
    this.subscription.unsubscribe();
  }

  async ngOnInit() {
    // Since ngOnInit() is executed before `deviceready` event,
    // you have to wait the event.
    await this.platform.ready();
    await this.loadMap();
  }

  loadMap() {
    const POINTS: BaseArrayClass<any> = new BaseArrayClass<any>([
      { position: { lat: 19.663012, lng: -99.02178 },
        icon: 'assets/icon/school.png', title: 'Secundaria | José Vasconcelos (Pública)' },
      { position: { lat: 19.661744, lng: -99.022754 },
        icon: 'assets/icon/school.png', title: 'Primaria | Vasco de Quiroga (Pública)' },
      { position: { lat: 19.661462, lng: -99.022855 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Federico Froebel (Pública)' },
      { position: { lat: 19.648039, lng: -99.019016 },
        icon: 'assets/icon/school.png', title: 'Primaria de tiempo completo | Francisco Gonzalez Bocanegra (Pública)' },
      { position: { lat: 19.647184, lng: -99.019243 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Amado Nervo (Pública)' },
      { position: { lat: 19.645499, lng: -99.01771 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria No. 223 María del Carmen Molina (Pública)' },
      { position: { lat: 19.644793, lng: -99.023376 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Sor Juana Inés de la Cruz (Pública)' },
      { position: { lat: 19.645056, lng: -99.022789 },
        icon: 'assets/icon/school.png', title: 'Primaria | Miguel de Cervantes Saavedra (Pública)' },
      { position: { lat: 19.64761, lng: -99.029688 },
        icon: 'assets/icon/school.png', title: 'Primaria | Laura Méndez de Cuenca (Pública)' },
      { position: { lat: 19.647505, lng: -99.030157 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Frida Khalo (Pública)' },
      { position: { lat: 19.647399, lng: -99.030889 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria No. 1111 Gabriel García Marquez (Pública)' },
      { position: { lat: 19.652406, lng: -99.029578 },
        icon: 'assets/icon/school.png', title: 'Primaria | José Vasconcelos (Pública)' },
      { position: { lat: 19.652167, lng: -99.030072 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Octavio Paz (Pública)' },
      { position: { lat: 19.654788, lng: -99.027468 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Federico Cantú (Pública)' },
      { position: { lat: 19.678095, lng: -98.998483 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ramón Morales (Pública)' },
      { position: { lat: 19.673619, lng: -99.000498 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Benito Juarez (Pública)' },
      { position: { lat: 19.674265, lng: -99.00024 },
        icon: 'assets/icon/school.png', title: 'Primaria | Francisco I. Madero (Turno Vespertino) (Pública)' },
      { position: { lat: 19.674265, lng: -99.00024 },
        icon: 'assets/icon/school.png', title: 'Primaria | Revolución Mexicana (Turno Matutino) (Pública)' },
      { position: { lat: 19.677614, lng: -98.992546 },
        icon: 'assets/icon/school.png', title: 'Primaria | Profesor Manuel Hinojosa Giles (Pública)' },
      { position: { lat: 19.674402, lng: -98.994486 },
        icon: 'assets/icon/school.png', title: 'Secundaria | General Felipe Ángeles (Pública)' },
      { position: { lat: 19.685333, lng: -98.999917 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | C.B.T. No 3. Tecámac (Pública)' },
      { position: { lat: 19.674028, lng: -98.997978 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Alejandro de Humboldt (Pública)' },
      { position: { lat: 19.66641, lng: -99.001908 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jesús F. Contreras (Pública)' },
      { position: { lat: 19.678831, lng: -99.000157 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio La Paz (Particular)' },
      { position: { lat: 19.679676, lng: -98.999476 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Federico Frobel (Particular)' },
      { position: { lat: 19.67778, lng: -98.997007 },
        icon: 'assets/icon/school.png', title: 'Primaria | Juan Pablo II (Particular)' },
      { position: { lat: 19.682579, lng: -99.000006 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | El Castillito (Particular)' },
      { position: { lat: 19.677692, lng: -98.999092 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jean Piaget (Particular)' },
      { position: { lat: 19.674339, lng: -98.99549 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Niños Héroes (Particular)' },
      { position: { lat: 19.670817, lng: -98.999053 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Bebe Einstein (Particular)' },
      { position: { lat: 19.671976, lng: -99.002549 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | David Alfaro Siqueiros (Particular)' },
      { position: { lat: 19.674637, lng: -98.999595 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Ratitos Felices (Particular)' },
      { position: { lat: 19.685239, lng: -98.988989 },
        icon: 'assets/icon/school.png', title: 'Primaria | Mariano Matamoros (Turno Matutino) (Pública)' },
      { position: { lat: 19.685239, lng: -98.988989 },
        icon: 'assets/icon/school.png', title: 'Primaria | Aquiles Serdán (Turno Vespertino) (Pública)' },
      { position: { lat: 19.684457, lng: -98.991303 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Real Campestre (Particular)' },
      { position: { lat: 19.682056, lng: -98.987782 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Efrén Rebolledo (Pública)' },
      { position: { lat: 19.681829, lng: -98.987239 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Francisco Primo de Verdad (Pública)' },
      { position: { lat: 19.686762, lng: -98.988428 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | ABC Colegio Montessori (Particular)' },
      { position: { lat: 19.680035, lng: -98.978258 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Colegio Ateneo Mexicano (Particular)' },
      { position: { lat: 19.680336, lng: -98.978054 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio Ateneo Mexicano (Particular)' },
      { position: { lat: 19.680649, lng: -98.977804 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Colegio Ateneo Mexicano (Particular)' },
      { position: { lat: 19.674722, lng: -98.975628 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Sec. Tec. 199 Miguel de Cervantes Saavedra (Pública)' },
      { position: { lat: 19.674345, lng: -98.974896 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Preparatoria 216 (Pública)' },
      { position: { lat: 19.672092, lng: -98.978039 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Instituto de Formación Integral Nouveu (Particular)' },
      { position: { lat: 19.671751, lng: -98.976493 },
        icon: 'assets/icon/school.png', title: 'Primaria | Luis Moya Regis (Pública)' },
      { position: { lat: 19.672475, lng: -98.979307 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Hellen Keller (DIF) (Pública)' },
      { position: { lat: 19.671105, lng: -98.973552 },
        icon: 'assets/icon/school.png', title: 'Primaria | 15 de Septiembre (Pública)' },
      { position: { lat: 19.670824, lng: -98.973073 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Laura Méndez de Cuenca (Pública)' },
      { position: { lat: 19.679175, lng: -98.981191 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Manuel Tolsá (Pública)' },
      { position: { lat: 19.679268, lng: -98.981615 },
        icon: 'assets/icon/school.png', title: 'Primaria | Mario Molina (Pública)' },
      { position: { lat: 19.690558, lng: -98.985866 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Amado Nervo (Pública)' },
      { position: { lat: 19.686918, lng: -98.985876 },
        icon: 'assets/icon/school.png', title: 'Primaria | Estado de México (Pública)' },
      { position: { lat: 19.687153, lng: -98.985735 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Olivio Lecroix (Pública)' },
      { position: { lat: 19.687851, lng: -98.98113 },
        icon: 'assets/icon/school.png', title: 'Primaria | Mario Molina (Pública)' },
      { position: { lat: 19.688047, lng: -98.981534 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ángel Garibay (Pública)' },
      { position: { lat: 19.684392, lng: -98.976481 },
        icon: 'assets/icon/school.png', title: 'Primaria | Cuitlahuac (Pública)' },
      { position: { lat: 19.68488, lng: -98.976198 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Mahatma Ghandi (Pública)' },
      { position: { lat: 19.714474, lng: -98.97816 },
        icon: 'assets/icon/school.png', title: 'Universidad | Universidad Politécnica de Tecámac (Pública)' },
      { position: { lat: 19.71362, lng: -98.973464 },
        icon: 'assets/icon/school.png', title: 'Universidad | Centro Iberomericano de Estudios Profesionales (Particular)' },
      { position: { lat: 19.707967, lng: -98.969829 },
        icon: 'assets/icon/school.png', title: 'Universidad | Universidad Privada del Estado de México (Particular)' },
      { position: { lat: 19.707616, lng: -98.977305 },
        icon: 'assets/icon/school.png', title: 'Universidad | Centro Universitario de América (Particular)' },
      { position: { lat: 19.709323, lng: -98.973245 },
        icon: 'assets/icon/school.png', title: 'Bachillerato y Universidad | ITEC (Particular)' },
      { position: { lat: 19.723396, lng: -98.971561 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | CECyTEM (Pública)' },
      { position: { lat: 19.709474, lng: -98.978933 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Escuela Normal de Tecámac (Pública)' },
      { position: { lat: 19.709345, lng: -98.974199 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Centro Cutural Mexiquense (Particular)' },
      { position: { lat: 19.709266, lng: -98.976767 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Esc. Sec. 103 Adolfo López Mateos (Pública)' },
      { position: { lat: 19.710527, lng: -98.968836 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Juan de Dios Pesa (Pública)' },
      { position: { lat: 19.719012, lng: -98.965108 },
        icon: 'assets/icon/school.png', title: 'Primaria | Mario Rojas (Turno Matutino) (Pública)' },
      { position: { lat: 19.719005, lng: -98.965146 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jorge Jimenez (Turno Vespertino) (Pública)' },
      { position: { lat: 19.719077, lng: -98.967274 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Isidro Fabela Alfaro (Pública)' },
      { position: { lat: 19.699437, lng: -98.941871 },
        icon: 'assets/icon/school.png', title: 'Primaria | María Montessori (Pública)' },
      { position: { lat: 19.698941, lng: -98.941659 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Elena Garro (Pública)' },
      { position: { lat: 19.71326, lng: -98.967876 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Josué Mirlo (Particular)' },
      { position: { lat: 19.717608, lng: -98.969077 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | María Montessori (Particular)' },
      { position: { lat: 19.720918, lng: -98.978222 },
        icon: 'assets/icon/school.png', title: 'Primaria | Emiliano Zapata (Pública)' },
      { position: { lat: 19.721841, lng: -98.97853 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Elisa Acuña y Rosetti (Pública)' },
      { position: { lat: 19.705276, lng: -98.958138 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Enrique Pestalozzi (Pública)' },
      { position: { lat: 19.734134, lng: -98.977091 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Juan Escutia (Pública)' },
      { position: { lat: 19.697181, lng: -98.965516 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Julio Verne (Particular)' },
      { position: { lat: 19.709527, lng: -98.971507 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Bachillerato Tecnológico Jhon Von Newman (Particular)' },
      { position: { lat: 19.695031, lng: -98.94102 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | DEMET (Pública)' },
      { position: { lat: 19.672189, lng: -98.959398 },
        icon: 'assets/icon/school.png', title: 'Primaria | José Maria Morelos y Pavón (Pública)' },
      { position: { lat: 19.667855, lng: -98.961905 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Ricardo Flores Magón (Pública)' },
      { position: { lat: 19.674029, lng: -98.957225 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ángel Salas Bonilla (Pública)' },
      { position: { lat: 19.674881, lng: -98.961874 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Rafael Martinez Castañeda (Pública)' },
      { position: { lat: 19.678695, lng: -98.968632 },
        icon: 'assets/icon/school.png', title: 'Primaria | Nezahualcóyotl (Pública)' },
      { position: { lat: 19.679577, lng: -98.966443 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Manuel Ávila Camacho (Pública)' },
      { position: { lat: 19.681289, lng: -98.97026 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Isidro Fabela (Pública)' },
      { position: { lat: 19.682595, lng: -98.973959 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jacinto López Moreno (Pública)' },
      { position: { lat: 19.683093, lng: -98.97369 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jacinto López Moreno (Pública)' },
      { position: { lat: 19.682089, lng: -98.974284 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Jacinto López Moreno (Pública)' },
      { position: { lat: 19.697247, lng: -98.977467 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | CONALEP (Pública)' },
      { position: { lat: 19.695003, lng: -98.976308 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Laura Méndez Cuenca (Pública)' },
      { position: { lat: 19.695601, lng: -98.977762 },
        icon: 'assets/icon/school.png', title: 'Primaria | Nueva Generación (Pública)' },
      { position: { lat: 19.695266, lng: -98.977949 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Agustín González (Pública)' },
      { position: { lat: 19.699466, lng: -98.975656 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Nehualcóyotl (Pública)' },
      { position: { lat: 19.698784, lng: -98.974554 },
        icon: 'assets/icon/school.png', title: 'Primaria | Alfredo del Mazo Velez (Pública)' },
      { position: { lat: 19.690605, lng: -98.983265 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | José María Pino Suarez (Pública)' },
      { position: { lat: 19.691095, lng: -98.979592 },
        icon: 'assets/icon/school.png', title: 'Primaria | Educadores del Tercer Mundo (Turno Matutino) (Pública)' },
      { position: { lat: 19.691095, lng: -98.979592 },
        icon: 'assets/icon/school.png', title: 'Primaria | Valentín Gómez Farías (Turno Vespertino) (Pública)' },
      { position: { lat: 19.687691, lng: -98.967046 },
        icon: 'assets/icon/school.png', title: 'Educación especial | Roberto Solis Quiroga (Pública)' },
      { position: { lat: 19.68658, lng: -98.967348 },
        icon: 'assets/icon/school.png', title: 'Primaria | Felipe Villanueva (Turno matutino) (Pública)' },
      { position: { lat: 19.68658, lng: -98.967348 },
        icon: 'assets/icon/school.png', title: 'Primaria | Lázaro Cárdenas del Río (Turno Vespertino) (Pública)' },
      { position: { lat: 19.688983, lng: -98.969404 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Escuela Preparatoria Oficial No. 73 (Pública)' },
      { position: { lat: 19.683886, lng: -98.965349 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Martín González Vázquez (Pública)' },
      { position: { lat: 19.691816, lng: -98.980354 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jorge Manriquez (Pública)' },
      { position: { lat: 19.690992, lng: -98.981491 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | El mundo del pequeño (Particular)' },
      { position: { lat: 19.691835, lng: -98.980322 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | J.N Alexander Fleming (Pública)' },
      { position: { lat: 19.762775, lng: -98.972865 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio Persa (Particular)' },
      { position: { lat: 19.727461, lng: -98.96438 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria #226 Pablo Latapí Serre (Pública)' },
      { position: { lat: 19.727471, lng: -98.963608 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ingacio Ramirez (Pública)' },
      { position: { lat: 19.728042, lng: -98.964369 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Lev Seminovich Vigotsky (Pública)' },
      { position: { lat: 19.762321, lng: -98.954715 },
        icon: 'assets/icon/school.png', title: 'Primaria | Justo Sierra (Turno Matutino y Vespertino) (Pública)' },
      { position: { lat: 19.763361, lng: -98.961944 },
        icon: 'assets/icon/school.png', title: 'Primaria | Unificación campesina (Pública)' },
      { position: { lat: 19.759544, lng: -98.965345 },
        icon: 'assets/icon/school.png', title: 'Primaria | Benito Juárez (Turno Matutino) (Pública)' },
      { position: { lat: 19.759544, lng: -98.965345 },
        icon: 'assets/icon/school.png', title: 'Primaria | Venustiano Carranza (Turno Vespertino) (Pública)' },
      { position: { lat: 19.75889, lng: -98.974861 },
        icon: 'assets/icon/school.png', title: 'Primaria | Marie Curie (Particular)' },
      { position: { lat: 19.758943, lng: -98.974578 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Marie Curie (Particular)' },
      { position: { lat: 19.740417, lng: -98.954893 },
        icon: 'assets/icon/school.png', title: 'Primaria | Narciso Mendoza (Turno matutino y vespertino) (Pública)' },
      { position: { lat: 19.741643, lng: -98.959141 },
        icon: 'assets/icon/school.png', title: 'Primaria | Carmen Serdán (Pública)' },
      { position: { lat: 19.736062, lng: -98.941662 },
        icon: 'assets/icon/school.png', title: 'Primaria | General León Guzmán Montes de Oca (Pública)' },
      { position: { lat: 19.734115, lng: -98.969654 },
        icon: 'assets/icon/school.png', title: 'Primaria | Carlos Fuentes Macías (Pública)' },
      { position: { lat: 19.743685, lng: -98.972639 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Escuela Secundaria General Base Aérea (Pública)' },
      { position: { lat: 19.743518, lng: -98.97113 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | CBT No. 2 Lic. Carlos Pichardo (Turno matutino y vespertino) (Pública)' },
      { position: { lat: 19.756577, lng: -98.964023 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | J.N. Leonardo Da Vinci (Pública)' },
      { position: { lat: 19.768938, lng: -98.959434 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Lic. Álvaro Gálvez y Fuentes (Pública)' },
      { position: { lat: 19.768517, lng: -98.959878 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Gral. Ignacio Zaragoza (Pública)' },
      { position: { lat: 19.761492, lng: -98.946719 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Lic. Benito Juárez (Pública)' },
      { position: { lat: 19.761492, lng: -98.946719 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Telebachillerato Comunitario No. 187 (Pública)' },
      { position: { lat: 19.743635, lng: -98.951925 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Telesecundaria Malitzin (Pública)' },
      { position: { lat: 19.740867, lng: -98.954721 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | José María Velasco (Pública)' },
      { position: { lat: 19.736419, lng: -98.940447 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Octavio Paz (Pública)' },
      { position: { lat: 19.763364, lng: -98.956795 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | José María Yañez (Pública)' },
      { position: { lat: 19.637927, lng: -99.047116 },
        icon: 'assets/icon/school.png', title: 'Universidad | Unidad de Estudio Superiores Tecámac (Pública)' },
      { position: { lat: 19.637024, lng: -99.045689 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Francisco Márquez (Pública)' },
      { position: { lat: 19.637784, lng: -99.045374 },
        icon: 'assets/icon/school.png', title: 'Primaria | Octavio Paz (Pública)' },
      { position: { lat: 19.639384, lng: -99.051722 },
        icon: 'assets/icon/school.png', title: 'Primaria | Carlos Fuentes (Pública)' },
      { position: { lat: 19.635738, lng: -99.039513 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Estacia Infantil Itzuri (Pública)' },
      { position: { lat: 19.635251, lng: -99.04003 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | COBAEM 35 (Pública)' },
      { position: { lat: 19.63668, lng: -99.036538 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria No. 211 (Pública)' },
      { position: { lat: 19.636803, lng: -99.035992 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primaria Laura Méndez de Cuenca (Pública)' },
      { position: { lat: 19.636352, lng: -99.031062 },
        icon: 'assets/icon/school.png', title: 'Primaria | Rosario Castellanos (Pública)' },
      { position: { lat: 19.636316, lng: -99.030443 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Niños Héroes (Pública)' },
      { position: { lat: 19.634083, lng: -99.029131 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria Gustavo Baz (Pública)' },
      { position: { lat: 19.641066, lng: -99.033617 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria No. 228 Sor Juana Inés de la Cruz (Pública)' },
      { position: { lat: 19.640994, lng: -99.032866 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primaria David Alfaro Siqueiros (Pública)' },
      { position: { lat: 19.640965, lng: -99.032236 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | David Paul Ausubel (Pública)' },
      { position: { lat: 19.644683, lng: -99.034376 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Jaime Torres Bodet (Pública)' },
      { position: { lat: 19.644056, lng: -99.034527 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Carlos Fuentes (Pública)' },
      { position: { lat: 19.643692, lng: -99.030022 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria 242 Gabriel García Márquez (Pública)' },
      { position: { lat: 19.641869, lng: -99.025656 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Nueva Creación (Pública)' },
      { position: { lat: 19.641582, lng: -99.026111 },
        icon: 'assets/icon/school.png', title: 'Primaria | Malinalli (Pública)' },
      { position: { lat: 19.778537, lng: -98.980773 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Repúblicas Unidas de América (Ambos turnos) (Pública)' },
      { position: { lat: 19.77828, lng: -98.980208 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Ricardo Flores Magón (Pública)' },
      { position: { lat: 19.775082, lng: -98.981422 },
        icon: 'assets/icon/school.png', title: 'Primaria | Gral. Lázaro Cárdenas (Turno Vespertino) (Pública)' },
      { position: { lat: 19.774696, lng: -98.979352 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Sor Juana Inés de la Cruz (Particular)' },
      { position: { lat: 19.772732, lng: -98.982077 },
        icon: 'assets/icon/school.png', title: 'Centro de estudios para adultos | CEAJA (Pública)' },
      { position: { lat: 19.772275, lng: -98.981782 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Kinder Carlos Mérida (Pública)' },
      { position: { lat: 19.775611, lng: -98.987781 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ferrocarriles Nacionales (Pública)' },
      { position: { lat: 19.775702, lng: -98.986952 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ferrocarriles Nacionales (Pública)' },
      { position: { lat: 19.767219, lng: -98.990752 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Juan Rosas Talavera (Pública)' },
      { position: { lat: 19.774914, lng: -98.985374 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Activo Pestalozzi (Particular)' },
      { position: { lat: 19.776817, lng: -98.976382 },
        icon: 'assets/icon/school.png',
        title: 'Secundaria | Escuela Secundaria Tecnica Industrial ' +
            'Comercial No.23 Felipe Villanueva (Turno matutino y vespertino (Pública)' },
      { position: { lat: 19.687468, lng: -98.994347 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jun Escutia (Pública)' },
      { position: { lat: 19.69106, lng: -98.998715 },
        icon: 'assets/icon/school.png', title: 'Primaria | Constitución de 1917 (Pública)' },
      { position: { lat: 19.691036, lng: -99.000487 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jaime Torres Bodet (Pública)' },
      { position: { lat: 19.691514, lng: -98.998598 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Heredia y Heredia (Pública)' },
      { position: { lat: 19.693086, lng: -99.003609 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Frida Khalo (Pública)' },
      { position: { lat: 19.693175, lng: -99.003971 },
        icon: 'assets/icon/school.png', title: 'Primaria | Patria Nueva (Pública)' },
      { position: { lat: 19.694717, lng: -99.007622 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Huehuetlahtolli (Pública)' },
      { position: { lat: 19.69504, lng: -99.008352 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Quetzal (Pública)' },
      { position: { lat: 19.674518, lng: -99.006102 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Maximiliano Ruiz Castañeda (Ambos Turnos) (Pública)' },
      { position: { lat: 19.674159, lng: -99.005095 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Escuela Preparatoria Oficial No. 22 (Ambos Turnos) (Pública)' },
      { position: { lat: 19.680479, lng: -99.0145 },
        icon: 'assets/icon/school.png', title: 'Primaria | Pentatlón Deportivo Militar Universitario (Pública)' },
      { position: { lat: 19.680217, lng: -99.013595 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Alberto G. Blanch (Pública)' },
      { position: { lat: 19.687354, lng: -99.012342 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Tomás Moro (Pública)' },
      { position: { lat: 19.680759, lng: -99.022394 },
        icon: 'assets/icon/school.png', title: 'Primaria y secundaria | Del Valle (Particular)' },
      { position: { lat: 19.683811, lng: -99.020226 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Franco Mexicano (Particular)' },
      { position: { lat: 19.685329, lng: -99.013844 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Universidad Tecnológica Internacionl (Particular)' },
      { position: { lat: 19.677115, lng: -99.021916 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Liceo México Americano (Particular)' },
      { position: { lat: 19.68163, lng: -99.029055 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ali Chumacero (Particular)' },
      { position: { lat: 19.684221, lng: -99.033599 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio Bilignüe Miguel de Cervantes Saavedra (Particular)' },
      { position: { lat: 19.693707, lng: -99.013342 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria Técnica No. 234 (Pública)' },
      { position: { lat: 19.69235, lng: -99.00871 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio Niños Héroes (Pública)' },
      { position: { lat: 19.687537, lng: -98.977636 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Gabriela Mistral (Pública)' },
      { position: { lat: 19.68493, lng: -98.970625 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ixtlamati (Pública)' },
      { position: { lat: 19.685295, lng: -98.971338 },
        icon: 'assets/icon/school.png', title: 'Primaria | Gral. Emiliano Zapata (Turno Vespertino) (Pública)' },
      { position: { lat: 19.685295, lng: -98.971338 },
        icon: 'assets/icon/school.png', title: 'Primaria | Prof. Otilio E. Montaño (Turno Matutino) (Pública)' },
      { position: { lat: 19.684732, lng: -98.973682 },
        icon: 'assets/icon/school.png', title: 'Primaria | Centro Pedagógico Felipe Villanueva (Particular)' },
      { position: { lat: 19.681309, lng: -98.965781 },
        icon: 'assets/icon/school.png', title: 'Secundaria | ESTIC 0022 Vicente Guerrero (Pública)' },
      { position: { lat: 19.682839, lng: -98.96057 },
        icon: 'assets/icon/school.png', title: 'Primaria | Vicente Guerrero (Pública)' },
      { position: { lat: 19.61856, lng: -99.024567 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Gabriela Mistral (Pública)' },
      { position: { lat: 19.618807, lng: -99.023961 },
        icon: 'assets/icon/school.png', title: 'Primaria | Enrique C. Rebsamen (Pública)' },
      { position: { lat: 19.619066, lng: -99.023352 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | María Montessori (Pública)' },
      { position: { lat: 19.624697, lng: -99.017126 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Mártires de Chicago (Pública)' },
      { position: { lat: 19.625241, lng: -99.017435 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Juana de Ibarbourou (Pública)' },
      { position: { lat: 19.624356, lng: -99.017716 },
        icon: 'assets/icon/school.png', title: 'Primaria | Lázaro Cárdenas (Pública)' },
      { position: { lat: 19.630771, lng: -99.021495 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños "Enrique Laubscher" (Pública)' },
      { position: { lat: 19.630244, lng: -99.021048 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primaria Federalizada José Vasconcelos (Pública)' },
      { position: { lat: 19.629178, lng: -99.01758 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | COBAEM 19 (Pública)' },
      { position: { lat: 19.629179, lng: -99.012155 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Francisco Gabilondo Soler (Pública)' },
      { position: { lat: 19.634031, lng: -99.018401 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | José Vasconcelos (Pública)' },
      { position: { lat: 19.633887, lng: -99.019158 },
        icon: 'assets/icon/school.png', title: 'Primaria | Nicolás Bravo (Pública)' },
      { position: { lat: 19.634648, lng: -99.019514 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Juan Rulfo (Pública)' },
      { position: { lat: 19.663262, lng: -99.032908 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Itzamna (Particular)' },
      { position: { lat: 19.658659, lng: -99.037785 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | José Vasconcelos (Pública)' },
      { position: { lat: 19.658873, lng: -99.038473 },
        icon: 'assets/icon/school.png', title: 'Primaria | Hellen Keller (Pública)' },
      { position: { lat: 19.663627, lng: -99.032895 },
        icon: 'assets/icon/school.png', title: 'Primaria | Josué Mirlo (Tiempo Completo) (Pública)' },
      { position: { lat: 19.664145, lng: -99.033296 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Marie Curie (Pública)' },
      { position: { lat: 19.65266, lng: -99.03698 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Justo Sierra (Pública)' },
      { position: { lat: 19.653081, lng: -99.035954 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Preparatoria 243 (Pública)' },
      { position: { lat: 19.653777, lng: -99.03561 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Carlos Monsiváis (Pública)' },
      { position: { lat: 19.648428, lng: -99.040224 },
        icon: 'assets/icon/school.png', title: 'Primaria | Joaquín Fernández de Lizardi (Pública)' },
      { position: { lat: 19.648794, lng: -99.040129 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ana Freud (Pública)' },
      { position: { lat: 19.658795, lng: -99.037332 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Colegio Simón Bolivar (Pública)' },
      { position: { lat: 19.632117, lng: -99.027145 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | CBT 4 (Pública)' },
      { position: { lat: 19.629887, lng: -99.02734 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Leona Vicario (Pública)' },
      { position: { lat: 19.629242, lng: -99.027176 },
        icon: 'assets/icon/school.png', title: 'Primaria | Andrés Henestrosa (Pública)' },
      { position: { lat: 19.628404, lng: -99.031201 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jaime Sabines (Pública)' },
      { position: { lat: 19.622378, lng: -99.035754 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria 214 Héroes de Independencia (Pública)' },
      { position: { lat: 19.622009, lng: -99.035277 },
        icon: 'assets/icon/school.png', title: 'Primaria | 13 de Septiembre (Pública)' },
      { position: { lat: 19.62162, lng: -99.034606 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Rosario Castellanos (Pública)' },
      { position: { lat: 19.629734, lng: -99.031195 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | CEDIT Centro de Desarrollo Integral Tecamac (Particular)' },
      { position: { lat: 19.631323, lng: -99.031483 },
        icon: 'assets/icon/school.png', title: 'Primaria | Guillermo Gonzáles Camarena (Pública)' },
      { position: { lat: 19.629658, lng: -99.035621 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños "Francisco León de la Barra" (Pública)' },
      { position: { lat: 19.629877, lng: -99.034936 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primaria Miguel de Cervantes (Pública)' },
      { position: { lat: 19.6303, lng: -99.034361 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Felipe Sánchez Solis (Pública)' },
      { position: { lat: 19.624996, lng: -99.030535 },
        icon: 'assets/icon/school.png', title: 'Primaria | Frida Khalo (Ambos turnos) (Pública)' },
      { position: { lat: 19.625321, lng: -99.03102 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria 225 (Ambos turnos) (Pública)' },
      { position: { lat: 19.624704, lng: -99.029965 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Leona Vicario (Pública)' },
      { position: { lat: 19.623099, lng: -99.033624 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Kinder y Primaria "Alessandro Botticelli" (Particular)' },
      { position: { lat: 19.618665, lng: -99.032859 },
        icon: 'assets/icon/school.png', title: 'Educación especial | CAM 51 (Pública)' },
      { position: { lat: 19.620013, lng: -99.031683 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Francisco González Bocanegra (Pública)' },
      { position: { lat: 19.61938, lng: -99.032891 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ehécatl (Ambos turnos) (Pública)' },
      { position: { lat: 19.618979, lng: -99.033569 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Frida Khalo (Pública)' },
      { position: { lat: 19.622739, lng: -99.040195 },
        icon: 'assets/icon/school.png', title: 'Primaria | Diego Rivera (Ambos turnos) (Pública)' },
      { position: { lat: 19.624232, lng: -99.039156 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Preparatoria Oficial 229 (Ambos turnos) (Pública)' },
      { position: { lat: 19.626208, lng: -99.042924 },
        icon: 'assets/icon/school.png', title: 'Primaria | Heriberto Enriquez Rodríguez (Pública)' },
      { position: { lat: 19.6268, lng: -99.041833 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Gabino Barreda (Pública)' },
      { position: { lat: 19.628236, lng: -99.044059 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Escuela Secundaria Técnica 229 Matilde Montoya L. (Pública)' },
      { position: { lat: 19.629316, lng: -99.041822 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primaria Ángela Peralta (Pública)' },
      { position: { lat: 19.63133, lng: -99.03747 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primaria Federal Ángel Ma. Garibay Kintana (Pública)' },
      { position: { lat: 19.634814, lng: -99.045219 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Los Héroes Tecámac V (Pública)' },
      { position: { lat: 19.635183, lng: -99.04545 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Paola Espinoza (Pública)' },
      { position: { lat: 19.623315, lng: -99.034007 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Colegio Alejandro Magno (Particular)' },
      { position: { lat: 19.629932, lng: -99.031671 },
        icon: 'assets/icon/school.png', title: 'Primaria | Simón Bolivar (Particular)' },
      { position: { lat: 19.62647, lng: -99.032294 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jean Piaget (Pública)' },
      { position: { lat: 19.625958, lng: -99.031492 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Ovidio Decroly (Pública)' },
      { position: { lat: 19.634774, lng: -99.02404 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Gabriela Mistral (Pública)' },
      { position: { lat: 19.635097, lng: -99.024638 },
        icon: 'assets/icon/school.png', title: 'Primaria | Jesús Reyes Heroles (Pública)' },
      { position: { lat: 19.635638, lng: -99.023052 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Mundo Feliz (Particular)' },
      { position: { lat: 19.636434, lng: -99.02367 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Estancia Infantil Analí (Particular)' },
      { position: { lat: 19.77799, lng: -99.024394 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria 0604 Ignacio Manuel Altamirano (Pública)' },
      { position: { lat: 19.775653, lng: -99.018546 },
        icon: 'assets/icon/school.png', title: 'Primaria | Benito Juárez (Pública)' },
      { position: { lat: 19.775432, lng: -99.018085 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Frida Khalo (Pública)' },
      { position: { lat: 19.784925, lng: -99.002203 },
        icon: 'assets/icon/school.png', title: 'Primaria | Rey Xolox (Pública)' },
      { position: { lat: 19.77708, lng: -99.003269 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Justo Sierra (Pública)' },
      { position: { lat: 19.776542, lng: -98.998874 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primeras Luces del Progreso (Turno matutino) (Pública)' },
      { position: { lat: 19.776542, lng: -98.998874 },
        icon: 'assets/icon/school.png', title: 'Primaria | Venustiano Carranza (Turno Vespertino) (Pública)' },
      { position: { lat: 19.775178, lng: -98.996675 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Benito Juárez (Pública)' },
      { position: { lat: 19.773529, lng: -99.00001 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Escuela Telesecundaria  Xolox (Pública)' },
      { position: { lat: 19.769434, lng: -99.007319 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ameyal (Pública)' },
      { position: { lat: 19.681316, lng: -99.037127 },
        icon: 'assets/icon/school.png', title: 'Primaria | Vanguardia Revolucionaria (Turno matutino) (Pública)' },
      { position: { lat: 19.681316, lng: -99.037127 },
        icon: 'assets/icon/school.png', title: 'Primaria | Belisario Dominguez (Turno vespertino) (Pública)' },
      { position: { lat: 19.682382, lng: -99.036642 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Felipe Villanueva (Pública)' },
      { position: { lat: 19.680991, lng: -99.035154 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Escuela Media Superior Del Valle (Particular)' },
      { position: { lat: 19.683868, lng: -99.034959 },
        icon: 'assets/icon/school.png', title: 'Estancia infantil | Estancia infantil Los Petis (Particular)' },
      { position: { lat: 19.679534, lng: -99.03019 },
        icon: 'assets/icon/school.png', title: 'Primaria | Sigmun Freud (Particular)' },
      { position: { lat: 19.678498, lng: -99.030529 },
        icon: 'assets/icon/school.png', title: 'Primaria | Ricardo Flores Magón (Turno matutino) (Pública)' },
      { position: { lat: 19.678498, lng: -99.030529 },
        icon: 'assets/icon/school.png', title: 'Primaria | Salvador Díaz Mirón (turno Vespertino) (Pública)' },
      { position: { lat: 19.67837, lng: -99.030308 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Ojo de Agua (Pública)' },
      { position: { lat: 19.679083, lng: -99.03714 },
        icon: 'assets/icon/school.png', title: 'Primaria y secundaria | Defensores de Anáhuac (Particular)' },
      { position: { lat: 19.676097, lng: -99.037013 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Juana de Asbaje (Particular)' },
      { position: { lat: 19.67598, lng: -99.036745 },
        icon: 'assets/icon/school.png', title: 'Primaria | Albert Einstein (Particular)' },
      { position: { lat: 19.676261, lng: -99.036603 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Bebé Einstein (Particular)' },
      { position: { lat: 19.675045, lng: -99.037319 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | C.B.T. No. 1 Jorge Jimenez Cantú (Ambos turnos) (Pública)' },
      { position: { lat: 19.673175, lng: -99.032213 },
        icon: 'assets/icon/school.png', title: 'Primaria | Rosaura Salazar (Particular)' },
      { position: { lat: 19.673037, lng: -99.031995 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de niños Faraday (Particular)' },
      { position: { lat: 19.673115, lng: -99.031945 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primaria Faraday (Particular)' },
      { position: { lat: 19.671815, lng: -99.025171 },
        icon: 'assets/icon/school.png', title: 'Primaria y secundaria | Colegio Miramar (Particular)' },
      { position: { lat: 19.671373, lng: -99.025808 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Rodolfo Neri (Pública)' },
      { position: { lat: 19.669218, lng: -99.024476 },
        icon: 'assets/icon/school.png', title: 'Secundaria y Bachillerato | Albert Einstein (Particular)' },
      { position: { lat: 19.671421, lng: -99.022908 },
        icon: 'assets/icon/school.png', title: 'Secundaria y Bachillerato | Benemérito de las Américas (Particular)' },
      { position: { lat: 19.671747, lng: -99.022722 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Instituto Formativo Activa (Particular)' },
      { position: { lat: 19.674075, lng: -99.025966 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria No. 39 Felipe Villanueva (Ambos turnos) (Pública)' },
      { position: { lat: 19.673564, lng: -99.023877 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Centro Educativo Kipling (Particular)' },
      { position: { lat: 19.675294, lng: -99.023543 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Liceo México Americano (Particular)' },
      { position: { lat: 19.67021, lng: -99.018447 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primara 12 de octubre de 1492 (Pública)' },
      { position: { lat: 19.67021, lng: -99.018447 },
        icon: 'assets/icon/school.png', title: 'Primaria | Escuela Primaria Miguel Hidalgo (Turno Vespertino) (Pública)' },
      { position: { lat: 19.670845, lng: -99.017891 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Ing. Manuel Gonzalez Flores (Pública)' },
      { position: { lat: 19.67139, lng: -99.017471 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Colegio México (Particular)' },
      { position: { lat: 19.673335, lng: -99.015307 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Pingos (Particular)' },
      { position: { lat: 19.673113, lng: -99.014881 },
        icon: 'assets/icon/school.png', title: 'Primaria | Generación 2000 (Particular)' },
      { position: { lat: 19.672711, lng: -99.011776 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Centro Educativo Kipling (Particular)' },
      { position: { lat: 19.676864, lng: -99.013437 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Ojo de Agua Integral Siglo XXI (Particular)' },
      { position: { lat: 19.676732, lng: -99.013561 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Centro de Estudios Intensivos Casa de Felipe Villanueva (Particular)' },
      { position: { lat: 19.678448, lng: -99.008627 },
        icon: 'assets/icon/school.png', title: 'Primaria | Colegio Carl Rogers (Particular)' },
      { position: { lat: 19.678411, lng: -99.015537 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Instituto Hellen Keller Adams (Particular)' },
      { position: { lat: 19.674355, lng: -99.034216 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Colegio Celestine Freinet (Particular)' },
      { position: { lat: 19.670168, lng: -99.022474 },
        icon: 'assets/icon/school.png', title: 'Universidad | Centro Escolar Newton (Particular)' },
      { position: { lat: 19.674088, lng: -99.023403 },
        icon: 'assets/icon/school.png', title: 'Mixto | Centro Educativo Erich Fromm (Particular)' },
      { position: { lat: 19.675652, lng: -99.020403 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Niños de América (Particular)' },
      { position: { lat: 19.675401, lng: -99.01905 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Indara (Particular)' },
      { position: { lat: 19.678984, lng: -99.025929 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Toltecáyotl (Particular)' },
      { position: { lat: 19.681199, lng: -99.030003 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Lord Baden Powell (Particular)' },
      { position: { lat: 19.676568, lng: -99.038317 },
        icon: 'assets/icon/school.png', title: 'Preescolar y Primaria | Intituto Integral Europeo (Particular)' },
      { position: { lat: 19.650028, lng: -99.009187 },
        icon: 'assets/icon/school.png', title: 'Secundaria | José María Morelos y Pavón (Pública)' },
      { position: { lat: 19.649748, lng: -99.011295 },
        icon: 'assets/icon/school.png', title: 'Primaria | Solidaridad 1990 (Ambos turnos) (Pública)' },
      { position: { lat: 19.653445, lng: -99.00796 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | María Enriqueta Camarillo (Pública)' },
      { position: { lat: 19.653273, lng: -99.007031 },
        icon: 'assets/icon/school.png', title: 'Telesecundaria | Telesecundaria General Felipe Ángeles (Pública)' },
      { position: { lat: 19.656396, lng: -99.008576 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primaria Felipe Villanueva (Pública)' },
      { position: { lat: 19.659792, lng: -99.009653 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Juan de Dios Castro (Pública)' },
      { position: { lat: 19.6606, lng: -99.010849 },
        icon: 'assets/icon/school.png', title: 'Primaria | Emiliano Zapata (Pública)' },
      { position: { lat: 19.664005, lng: -99.008338 },
        icon: 'assets/icon/school.png', title: 'Primaria | Rosario Castellanos (Pública)' },
      { position: { lat: 19.665526, lng: -99.005587 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de niños José María Luis Mora (Pública)' },
      { position: { lat: 19.668485, lng: -99.008582 },
        icon: 'assets/icon/school.png', title: 'Educación especial | José Clemente Orozco (Pública)' },
      { position: { lat: 19.662352, lng: -98.994056 },
        icon: 'assets/icon/school.png', title: 'Bachillerato | Escuela Preparatoria Oficial No. 179' +
            ' Tlatelolco 2 de Octubre de 1968 (Pública)' },
      { position: { lat: 19.659619, lng: -98.995214 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Rosario Castellanos (Ambos turnos) (Pública)' },
      { position: { lat: 19.659242, lng: -98.995444 },
        icon: 'assets/icon/school.png', title: 'Primaria | Sor Juana Inés de la Cruz (Ambos turnos) (Pública)' },
      { position: { lat: 19.658355, lng: -98.995782 },
        icon: 'assets/icon/school.png', title: 'Secundaria | José Vasconcelos (Pública)' },
      { position: { lat: 19.659297, lng: -98.991361 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Rosaura Zapata (Pública)' },
      { position: { lat: 19.659261, lng: -98.99185 },
        icon: 'assets/icon/school.png', title: 'Primaria | Lic. Adolfo López Mateos (Ambos turnos) (Pública)' },
      { position: { lat: 19.660059, lng: -98.99297 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Escuela Secundaria Oficial No.0819 Rosario Castellanos (Pública)' },
      { position: { lat: 19.653513, lng: -98.992939 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de Niños Frida Khalo (Pública)' },
      { position: { lat: 19.653886, lng: -98.9931 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Secundaria 1014 Jose Maria De Heredia Y Heredia (Pública)' },
      { position: { lat: 19.654091, lng: -98.993176 },
        icon: 'assets/icon/school.png', title: 'Primaria | Primaria Emiliano Zapata (Ambos turnos) (Pública)' },
      { position: { lat: 19.653615, lng: -98.981614 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | María Ross Londa (Pública)' },
      { position: { lat: 19.652676, lng: -98.982113 },
        icon: 'assets/icon/school.png', title: 'Primaria | Alfonso García Robles (Pública)' },
      { position: { lat: 19.671458, lng: -98.976777 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Vasco de Quiroga (Pública)' },
      { position: { lat: 19.711144, lng: -98.969283 },
        icon: 'assets/icon/school.png', title: 'Primaria | Doctor Gustavo Baz (Pública)' },
      { position: { lat: 19.775082, lng: -98.981422 },
        icon: 'assets/icon/school.png', title: 'Primaria | José María Morelos y Pavón (Turno Matutino) (Pública)' },
      { position: { lat: 19.628562, lng: -99.011637 },
        icon: 'assets/icon/school.png', title: 'Primaria | Gabriela Mistral (Pública)' },
      { position: { lat: 19.650125, lng: -99.011639 },
        icon: 'assets/icon/school.png', title: 'Jardín de niños | Jardín de niños Motolinia (Pública)' },
      { position: { lat: 19.653229, lng: -98.981976 },
        icon: 'assets/icon/school.png', title: 'Secundaria | Mahatma Ghandi (Pública)' },
    ]);

    this.map = GoogleMaps.create('map_canvas', {
      camera: {
        target: this.cuadrantes[10]
      },
      controls: {
        'myLocationButton': true,
        'myLocation': true,
      },
    });

    /* for ( let i = 0; i < this.cuadrantes.length; i++ ) {
      this.map.addPolygonSync({
        'points': this.cuadranteActual,
        'strokeColor' : 'rgba(84,0,14)',
        'fillColor' : 'rgba(84,0,14,0.2)',
        'strokeWidth': 3
      });
     }*/

    POINTS.forEach((data: any) => {
      data.disableAutoPan = true;
      this.map.addMarkerSync(data)
      .on(GoogleMapsEvent.INFO_CLICK).subscribe((params) => {
        console.log(params);
          this.subscription.unsubscribe();
        this.presentModal(params);
      });
    });

    /*const points: BaseArrayClass<ILatLng> = polygon.getPoints();

    points.forEach((latLng: ILatLng, idx: number) => {
      const marker: Marker = this.map.addMarkerSync({
        draggable: true,
        position: latLng
      });
      marker.on(GoogleMapsEvent.MARKER_DRAG).subscribe((params) => {
        const position: LatLng = params[0];
        points.setAt(idx, position);
      });
    });*/

  }

}
